config/routes.rb
Rails.application.routes.draw do
  # resources :fares
  resources :fares
  devise_for :users
  resources :reports

  root 'reports#index'
  
  as :user do
  	get "/jnc_sign_up" => "devise/registrations#new"
  end

  as :fare do
  	get "/current_fare" => "fares#currentFare"
  end

end

app/models/fare.rb
class Fare < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fares_controller.rb
class FaresController < ApplicationController
  before_action :set_fare, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :new, :edit, :update, :destroy ]

  # GET /fares
  # GET /fares.json
  def index
    @fares = Fare.all.order("id DESC ")
  end

  # GET /fares/1
  # GET /fares/1.json
  def show
    
  end

  def currentFare
    @fare = Fare.last
   render :json => @fare
    # format.json { render :show, location: @fare }
  end


  # GET /fares/new
  def new
    @fare = Fare.new
  end

  # GET /fares/1/edit
  def edit
  end

  # POST /fares
  # POST /fares.json
  def create
    @fare = Fare.new(fare_params)

    respond_to do |format|
      if @fare.save
        format.html { redirect_to @fare, notice: 'Fare was successfully created.' }
        format.json { render :show, status: :created, location: @fare }
      else
        format.html { render :new }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fares/1
  # PATCH/PUT /fares/1.json
  def update
    respond_to do |format|
      if @fare.update(fare_params)
        format.html { redirect_to @fare, notice: 'Fare was successfully updated.' }
        format.json { render :show, status: :ok, location: @fare }
      else
        format.html { render :edit }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fares/1
  # DELETE /fares/1.json
  def destroy
    @fare.destroy
    respond_to do |format|
      format.html { redirect_to fares_url, notice: 'Fare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fare
      @fare = Fare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fare_params
      params.require(:fare).permit(:farePriceReg, :farePriceSp, :fareIncReg, :fareIncSp, :fareDescription)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :new, :edit, :update, :destroy ]
  protect_from_forgery with: :null_session

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all.order("created_at DESC")
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    
    respond_to do |format|
      if @report.save
        # format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def delete_all
  #   # @reports = Report.all
  #   @report.destroy_all
  #   respond_to do |format|
  #     format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fares_helper.rb
module FaresHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/fares/_form.html.erb
<%= form_for(@fare) do |f| %>
  <% if @fare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fare.errors.count, "error") %> prohibited this fare from being saved:</h2>

      <ul>
      <% @fare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :farePriceReg %><br>
    <%= f.text_field :farePriceReg %>
  </div>
  <div class="field">
    <%= f.label :farePriceSp %><br>
    <%= f.text_field :farePriceSp %>
  </div>
  <div class="field">
    <%= f.label :fareIncReg %><br>
    <%= f.text_field :fareIncReg %>
  </div>
  <div class="field">
    <%= f.label :fareIncSp %><br>
    <%= f.text_field :fareIncSp %>
  </div>
  <div class="field">
    <%= f.label :fareDescription %><br>
    <%= f.text_area :fareDescription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fares/edit.html.erb
<h1>Editing Fare</h1>

<%= render 'form' %>

<%= link_to 'Show', @fare %> |
<%= link_to 'Back', fares_path %>

app/views/fares/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="centerText">Listing Fares</h1>

<table class="table fareTable">
  <thead>
    <tr>
      <th>Fare Price Regular</th>
      <th>Fare Price Special Privilege</th>
      <th>Fare Increment Regula</th>
      <th>Fare Increment Special Privilege</th>
      <th>Fare Description</th>
      <th>Date </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fares.each do |fare| %>
      <tr>
        <td><%= fare.farePriceReg %></td>
        <td><%= fare.farePriceSp %></td>
        <td><%= fare.fareIncReg %></td>
        <td><%= fare.fareIncSp %></td>
        <td><%= fare.fareDescription %></td>
        <td><%= fare.created_at %></td>
        
        <% if user_signed_in? %>
          <td><%= link_to 'Show', fare %></td>
          <td><%= link_to 'Edit', edit_fare_path(fare) %></td>
          <td><%= link_to 'Destroy', fare, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'Create New Fare', new_fare_path %>
<% end %>

app/views/fares/new.html.erb
<h1>New Fare</h1>

<%= render 'form' %>

<%= link_to 'Back', fares_path %>

app/views/fares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Farepricereg:</strong>
  <%= @fare.farePriceReg %>
</p>

<p>
  <strong>Farepricesp:</strong>
  <%= @fare.farePriceSp %>
</p>

<p>
  <strong>Fareincreg:</strong>
  <%= @fare.fareIncReg %>
</p>

<p>
  <strong>Fareincsp:</strong>
  <%= @fare.fareIncSp %>
</p>

<p>
  <strong>Faredescription:</strong>
  <%= @fare.fareDescription %>
</p>

<%= link_to 'Edit', edit_fare_path(@fare) %> |
<%= link_to 'Back', fares_path %>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-default navbar-jnc">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <b class ="brand" >JeepNiCagayan</b>
      </a>
      
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li>  
          <a class="" href="<%= fares_path %>">
            <b class ="brand" >Fares</b>
          </a>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          
          <li>
            <%= link_to " Sign out", destroy_user_session_path, method: :delete, class: "fa fa-sign-out userOption" %>
          </li>

        <% else %>
          <!-- <li>
            <%= link_to " Sign up", new_user_registration_path, class: "fa fa-user-plus" %>
          </li> -->
          
          <li>
            <%= link_to " Sign in", new_user_session_path, class: "fa fa-sign-in" %>
          </li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JeepNiCagayanWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="bodyContainer ">
	<%= render 'layouts/header' %>
	
	
		<span class="alert"><%= alert %></span>
		<%= yield %>
	</div>
</body>
</html>

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="centerText mainTitle">Feedback logs</h1>

<main class="reportsContainer">
  <% if @reports != nil %>
    <% @reports.each do |report| %>
      
      <article class="reports centerContainer1">
        
        <% if user_signed_in? %>
          <div class="deleteBtnContainerRigth centerText">
          <%= link_to(report, method: :delete, data: { confirm: 'Want delete this ?' }) do %>
            <div class="deleteBtn">
            X
            </div>
          <% end %>   
          </div>
        <% end %>

        <%= link_to(report) do %>
          <h4><%= report.title %></h4>
          <p class="indentText"><%= report.description %></p>
          <date><%= time_ago_in_words(report.created_at) %></date>
        <% end %>
        
      </article>
    
    <% end %>

    <div id="gradient">
    </div>

  <% else %>

    <article class="reports centerContainer1">
      no feed back found
    </article>

  <% end %>    <!-- endof if statement for checker if reports is null/nil-->
</main>


<% if user_signed_in? %>
  <%= link_to 'New Report', new_report_path %>
<% end %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to(reports_path) do %>
	<button class="btn btn-primary	">Back</button>
<% end %>

<article class="showReport centerText">
	<p class="itemContainerRigth">
		<date><%= time_ago_in_words(@report.created_at) %> Ago</date>
	</p>
	<h1>  
	  <%= @report.title %>
	</h1>

	<p>
	  <strong>Description:</strong>
	  <%= @report.description %>
	</p>
	
	<% if user_signed_in? %>
	<%= link_to 'Edit', edit_report_path(@report) %>
	<% end %>
</article>